server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass http://auth-service:5001;
        proxy_set_header Host $host;
    }

    location /api/lists/ {
        proxy_pass http://lists-service:5002;
        proxy_set_header Host $host;
    }

    location /api/meals/ {
        proxy_pass http://meals-service:5003;
        proxy_set_header Host $host;
    }

    location /api/users/ {
        proxy_pass http://users-service:5004;
        proxy_set_header Host $host;
    }

    location /api/groups/ {
        proxy_pass http://group-service:5005;
        proxy_set_header Host $host;
    }
}
