"""
shared/jwt_utils.py  (FIXED)
-----------------------------
Original used 'default-secret-key' as fallback.
Auth service uses 'wams-jwt-secret-2025-change-in-prod'.
They must match — both now read from the same JWT_SECRET env var
with the same default so tokens generated by auth-service are accepted
by lists-service, meals-service, and users-service.
"""

import jwt
import os

JWT_SECRET = os.getenv('JWT_SECRET', 'wams-jwt-secret-2025-change-in-prod')
ALGORITHM  = 'HS256'


def decode_token(token: str):
    """
    Decode and validate a JWT produced by the auth-service.
    Returns (payload_dict, None) on success, (None, error_str) on failure.
    """
    try:
        payload = jwt.decode(token, JWT_SECRET, algorithms=[ALGORITHM])
        return payload, None
    except jwt.ExpiredSignatureError:
        return None, 'Token expired'
    except jwt.InvalidTokenError as e:
        return None, f'Invalid token: {e}'
