input {
  udp {
    port  => 5000
    codec => json
  }
}

filter {
  mutate {
    add_field => { "app" => "wams" }
  }
}

output {
  elasticsearch {
    hosts    => ["http://elasticsearch:9200"]
    index    => "wams-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }  # visible dans docker logs logstash
}